#!/bin/bash
cp ./compile ../../spl/
chmod +x ../../spl/compile
cd ../../spl/ && ./compile
cd ../Programs/Module8/
cp ./xfs ../../xfs-interface/
chmod +x ../../xfs-interface/xfs
cd ../../xfs-interface/ && ./xfs
cd ../xsm/ && ./xsm