./spl ../MyLabs/Lab18/timer_interrupt.spl
./spl ../MyLabs/Lab18/read_interrupt_int6.spl
./spl ../MyLabs/Lab18/write_interrupt_int7.spl
./spl ../MyLabs/Lab18/device_manager_module4.spl
./spl ../MyLabs/Lab18/resource_manager_module0.spl
./spl ../MyLabs/Lab18/boot_module.spl
./spl ../MyLabs/Lab18/scheduler_module5.spl
./spl ../MyLabs/Lab18/os_startup.spl
./spl ../MyLabs/Lab18/int10_module.spl
./spl ../MyLabs/Lab18/console_interrupt_handler.spl
./spl ../MyLabs/Lab18/process_manager_module1.spl
./spl ../MyLabs/Lab18/memory_manager_module2.spl
./spl ../MyLabs/Lab18/exec_interrupt9.spl
./spl ../MyLabs/Lab18/disk_interrupt_handler.spl