#!/bin/bash
./spl ../Programs/Module15/Main/haltprog.spl
./spl ../Programs/Module15/Main/os_startup.spl
./spl ../Programs/Module15/Main/timer.spl
./spl ../Programs/Module15/Main/int7.spl
./spl ../Programs/Module15/Main/boot.spl
./spl ../Programs/Module15/Main/int10.spl
./spl ../Programs/Module15/Main/scheduler.spl
./spl ../Programs/Module15/Main/module_0.spl
./spl ../Programs/Module15/Main/module_4.spl
