#!/bin/bash
./spl ../Programs/Module24/Main/haltprog.spl
./spl ../Programs/Module24/Main/os_startup.spl
./spl ../Programs/Module24/Main/timer.spl
./spl ../Programs/Module24/Main/int7.spl
./spl ../Programs/Module24/Main/boot.spl
./spl ../Programs/Module24/Main/int10.spl
./spl ../Programs/Module24/Main/scheduler.spl
./spl ../Programs/Module24/Main/module_0.spl
./spl ../Programs/Module24/Main/module_4.spl
./spl ../Programs/Module24/Main/console.spl
./spl ../Programs/Module24/Main/int6.spl
./spl ../Programs/Module24/Main/int9.spl
./spl ../Programs/Module24/Main/module_1.spl
./spl ../Programs/Module24/Main/module_2.spl
./spl ../Programs/Module24/Main/diskint.spl
./spl ../Programs/Module24/Main/int8.spl
./spl ../Programs/Module24/Main/int11.spl
./spl ../Programs/Module24/Main/int15.spl
./spl ../Programs/Module24/Main/int13.spl
./spl ../Programs/Module24/Main/int14.spl
./spl ../Programs/Module24/Main/exe_handler.spl
./spl ../Programs/Module24/Main/int4.spl
./spl ../Programs/Module24/Main/int5.spl
./spl ../Programs/Module24/Main/module_3.spl


