./spl ../MyLabs/Lab17/timer_interrupt.spl
./spl ../MyLabs/Lab17/read_interrupt_int6.spl
./spl ../MyLabs/Lab17/write_interrupt_int7.spl
./spl ../MyLabs/Lab17/device_manager_module4.spl
./spl ../MyLabs/Lab17/resource_manager_module0.spl
./spl ../MyLabs/Lab17/boot_module.spl
./spl ../MyLabs/Lab17/scheduler_module5.spl
./spl ../MyLabs/Lab17/os_startup.spl
./spl ../MyLabs/Lab17/int10_module.spl
./spl ../MyLabs/Lab17/console_interrupt_handler.spl
./spl ../MyLabs/Lab17/process_manager_module1.spl
./spl ../MyLabs/Lab17/memory_manager_module2.spl
./spl ../MyLabs/Lab17/exec_interrupt9.spl