#!/bin/bash
./xfs-interface fdisk
./xfs-interface load --exec ../Programs/Module22/A1/even.xsm
./xfs-interface load --exec ../Programs/Module22/A1/odd.xsm
./xfs-interface load --exec ../Programs/Module22/A1/rw.xsm
./xfs-interface load --init ../Programs/Module22/A1/init.xsm
./xfs-interface load --idle ../Programs/Module22/A1/idle.xsm
./xfs-interface load --int=10 ../Programs/Module22/A1/int10.xsm
./xfs-interface load --exhandler ../Programs/Module22/A1/exe_handler.xsm
./xfs-interface load --os ../Programs/Module22/A1/os_startup.xsm
./xfs-interface load --library ../expl/library.lib
./xfs-interface load --int=timer ../Programs/Module22/A1/timer.xsm
./xfs-interface load --int=7 ../Programs/Module22/A1/int7.xsm
./xfs-interface load --module 7 ../Programs/Module22/A1/boot.xsm
./xfs-interface load --module 5 ../Programs/Module22/A1/scheduler.xsm
./xfs-interface load --module 0 ../Programs/Module22/A1/module_0.xsm
./xfs-interface load --module 4 ../Programs/Module22/A1/module_4.xsm
./xfs-interface load --int=6 ../Programs/Module22/A1/int6.xsm
./xfs-interface load --int=console ../Programs/Module22/A1/console.xsm
./xfs-interface load --int=9 ../Programs/Module22/A1/int9.xsm
./xfs-interface load --int=8 ../Programs/Module22/A1/int8.xsm
./xfs-interface load --module 1 ../Programs/Module22/A1/module_1.xsm
./xfs-interface load --module 2 ../Programs/Module22/A1/module_2.xsm
./xfs-interface load --int=disk ../Programs/Module22/A1/diskint.xsm
./xfs-interface load --int=11 ../Programs/Module22/A1/int11.xsm
./xfs-interface load --int=15 ../Programs/Module22/A1/int15.xsm
./xfs-interface load --int=13 ../Programs/Module22/A1/int13.xsm
./xfs-interface load --int=14 ../Programs/Module22/A1/int14.xsm

./xfs-interface dump --inodeusertable
mv inodeusertable.txt ../Programs/Module22/A1/inodeusertable.txt

