#!/bin/bash
./xfs-interface load --init ../Programs/Module13/Main/numbers.xsm
./xfs-interface load --idle ../Programs/Module13/Main/idle.xsm
./xfs-interface load --int=10 ../Programs/Module13/Main/haltprog.xsm
./xfs-interface load --exhandler ../Programs/Module13/Main/haltprog.xsm
./xfs-interface load --os ../Programs/Module13/Main/os_startup.xsm
./xfs-interface load --library ../expl/library.lib
./xfs-interface load --int=timer ../Programs/Module13/Main/timer.xsm
./xfs-interface load --int=7 ../Programs/Module13/Main/print.xsm
./xfs-interface load --module 7 ../Programs/Module13/Main/boot.xsm

