#!/bin/bash
./xfs-interface fdisk
# ./xfs-interface load --exec ../Programs/Module17/Main/even.xsm
./xfs-interface load --init ../Programs/Module17/Main/odd.xsm
./xfs-interface load --idle ../Programs/Module17/Main/idle.xsm
./xfs-interface load --int=10 ../Programs/Module17/Main/int10.xsm
./xfs-interface load --exhandler ../Programs/Module17/Main/haltprog.xsm
./xfs-interface load --os ../Programs/Module17/Main/os_startup.xsm
./xfs-interface load --library ../expl/library.lib
./xfs-interface load --int=timer ../Programs/Module17/Main/timer.xsm
./xfs-interface load --int=7 ../Programs/Module17/Main/int7.xsm
./xfs-interface load --module 7 ../Programs/Module17/Main/boot.xsm
./xfs-interface load --module 5 ../Programs/Module17/Main/scheduler.xsm
./xfs-interface load --module 0 ../Programs/Module17/Main/module_0.xsm
./xfs-interface load --module 4 ../Programs/Module17/Main/module_4.xsm
./xfs-interface load --int=6 ../Programs/Module17/Main/int6.xsm
./xfs-interface load --int=console ../Programs/Module17/Main/console.xsm
./xfs-interface load --int=9 ../Programs/Module17/Main/int9.xsm
./xfs-interface load --module 1 ../Programs/Module17/Main/module_1.xsm
./xfs-interface load --module 2 ../Programs/Module17/Main/module_2.xsm

./xfs-interface dump --inodeusertable
mv inodeusertable.txt ../Programs/Module17/Main/inodeusertable.txt

