#!/bin/bash
cp ./compile ../../../spl/
chmod +x ../../../spl/compile
cd ../../../spl/ && ./compile
cd ../Programs/Module11/Main/

cp ./compile_expl ../../../expl/
chmod +x ../../../expl/compile_expl
cd ../../../expl/ && ./compile_expl
cd ../Programs/Module11/Main/

cp ./xfs ../../../xfs-interface/
chmod +x ../../../xfs-interface/xfs
cd ../../../xfs-interface/ && ./xfs
cd ../xsm/ && ./xsm --timer 1000