#!/bin/bash
./xfs-interface fdisk
./xfs-interface load --exec ../Programs/Module14/Main/even.xsm
./xfs-interface load --init ../Programs/Module14/Main/odd.xsm
./xfs-interface load --idle ../Programs/Module14/Main/idle.xsm
./xfs-interface load --int=10 ../Programs/Module14/Main/int10.xsm
./xfs-interface load --exhandler ../Programs/Module14/Main/haltprog.xsm
./xfs-interface load --os ../Programs/Module14/Main/os_startup.xsm
./xfs-interface load --library ../expl/library.lib
./xfs-interface load --int=timer ../Programs/Module14/Main/timer.xsm
./xfs-interface load --int=7 ../Programs/Module14/Main/print.xsm
./xfs-interface load --module 7 ../Programs/Module14/Main/boot.xsm
./xfs-interface load --module 5 ../Programs/Module14/Main/scheduler.xsm
./xfs-interface dump --inodeusertable
mv inodeusertable.txt ../Programs/Module14/Main/inodeusertable.txt

