#!/bin/bash
./xfs-interface fdisk
./xfs-interface load --exec ../Programs/Module23/A2/even.xsm
./xfs-interface load --exec ../Programs/Module23/A2/odd.xsm
./xfs-interface load --init ../Programs/Module23/A2/init.xsm
./xfs-interface load --idle ../Programs/Module23/A2/idle.xsm
./xfs-interface load --exec ../Programs/Module23/A2/file.xsm
./xfs-interface load --int=10 ../Programs/Module23/A2/int10.xsm
./xfs-interface load --exhandler ../Programs/Module23/A2/exe_handler.xsm
./xfs-interface load --os ../Programs/Module23/A2/os_startup.xsm
./xfs-interface load --library ../expl/library.lib
./xfs-interface load --int=timer ../Programs/Module23/A2/timer.xsm
./xfs-interface load --int=7 ../Programs/Module23/A2/int7.xsm
./xfs-interface load --module 7 ../Programs/Module23/A2/boot.xsm
./xfs-interface load --module 5 ../Programs/Module23/A2/scheduler.xsm
./xfs-interface load --module 0 ../Programs/Module23/A2/module_0.xsm
./xfs-interface load --module 4 ../Programs/Module23/A2/module_4.xsm
./xfs-interface load --int=6 ../Programs/Module23/A2/int6.xsm
./xfs-interface load --int=console ../Programs/Module23/A2/console.xsm
./xfs-interface load --int=9 ../Programs/Module23/A2/int9.xsm
./xfs-interface load --int=8 ../Programs/Module23/A2/int8.xsm
./xfs-interface load --module 1 ../Programs/Module23/A2/module_1.xsm
./xfs-interface load --module 2 ../Programs/Module23/A2/module_2.xsm
./xfs-interface load --int=disk ../Programs/Module23/A2/diskint.xsm
./xfs-interface load --int=11 ../Programs/Module23/A2/int11.xsm
./xfs-interface load --int=15 ../Programs/Module23/A2/int15.xsm
./xfs-interface load --int=13 ../Programs/Module23/A2/int13.xsm
./xfs-interface load --int=14 ../Programs/Module23/A2/int14.xsm
./xfs-interface load --int=4 ../Programs/Module23/A2/int4.xsm

./xfs-interface dump --inodeusertable
mv inodeusertable.txt ../Programs/Module23/A2/inodeusertable.txt

