./spl ../MyLabs/Lab19/timer_interrupt.spl
./spl ../MyLabs/Lab19/read_interrupt_int6.spl
./spl ../MyLabs/Lab19/write_interrupt_int7.spl
./spl ../MyLabs/Lab19/device_manager_module4.spl
./spl ../MyLabs/Lab19/resource_manager_module0.spl
./spl ../MyLabs/Lab19/boot_module.spl
./spl ../MyLabs/Lab19/scheduler_module5.spl
./spl ../MyLabs/Lab19/os_startup.spl
./spl ../MyLabs/Lab19/int10_module.spl
./spl ../MyLabs/Lab19/console_interrupt_handler.spl
./spl ../MyLabs/Lab19/process_manager_module1.spl
./spl ../MyLabs/Lab19/memory_manager_module2.spl
./spl ../MyLabs/Lab19/exec_interrupt9.spl
./spl ../MyLabs/Lab19/disk_interrupt_handler.spl
./spl ../MyLabs/Lab19/exhandler.spl